# Initialization parameters
input: akg_nhie.csv                    # Path to protein csv, single PDB, or list of PDBs [PDB1, PDB2, PDB3]
output_dir: dataset/v1                 # Path to save the generated clusters
modeller: true                         # Model missing loops
protoss: true                          # Assign protonation states
coordination: true                     # Generate clusters
skip: all                              # Skip 'modeller', 'protoss', or 'all' jobs if they already exist
optimize_select_residues: 1            # Modeller to model no (0), missing (1), or all (2) residues

# Cluster model parameters
max_atom_count: 750            
center_residues: [FE, FE2]             # Residue name to use as the cluster center
number_of_spheres: 3                   # Coordination spheres to generate
radius_of_first_sphere: 4.0            # Distance based cut off to determine first sphere
additional_ligands: []                 # Residues beyond first sphere to include
include_ligands: 2                     # Only ligands and waters in first sphere (0), Only non-water ligands (1), Everything (2)
capping_method: 1                      # Cap residues with None (0), hydrogens (1), ACE/NME (2)
smoothing_method: 2                    # Smoothing method Box plot (0), DBSCAN (1), [Dummy Atom] (2), None (3)

# Output parameters                               
compute_charges: true                  # Calculate charges using Protoss output
count_residues: true                   # Count the number of residues
write_xyz: true                        # Write out xyz files

# Create QM job files
optimization: false                    # Optimization (true) or single point (false)
method: ub3lyp                         # Functional to use
basis: lacvps_ecp                      # Basis set to use
guess: generate                        # Method for initial guess
gpus: 1                                # How many GPUs to use
memory: 4G                             # How much memory to use
checkup: true                          # Check how status of qm jobs
charge_embedding: true                 # Prepare QM with charge embedding
scheduler: slurm                       # What scheduler do you use (e.g., slurm, sge)
pcm_radii_file: /path/to/pcm_radii     # The path to the pcm_radii file if using terachem

# Submit QM jobs
submit_jobs: true                      # Submit the created jobs
job_count: 10                          # The number of jobs to maintain on the scheduler