# Parse configuration parameters
input: ./protein_master_list.txt            # Path to your list of proteins or a list of PDB ID's PDB1, PDB2, PDB3
output_dir: ./dataset/test-v1               # Path to save the generated clusters
modeller: true                              # Model missing loops
protoss: true                               # Assign protonation states
coordination: true                          # Generate clusters
skip: true                                  # Check for an existing job
optimize_select_residues: 1                 # Modeller to model no (0), missing (1), or all (2) residues

# Parameters for coordination spheres                       
active_site_metals: [FE, FE2]               # Metal residue names to look for
number_of_spheres: 2                        # Coordination spheres to generate
radius_of_first_sphere: 4.0                 # Distance based cut off to determine first sphere
additional_ligands: []                      # Residues beyond first sphere to include
capping_method: 1                           # Cap residues with None (0), hydrogens (1), ACE/NME (2)
smoothing_method: 2                         # Smoothing method Box plot (0), DBSCAN (1), [Dummy Atom] (2), None (3)

# Additional parameters                                         
compute_charges: true                       # Calculate charges using Protoss output
count_residues: true                        # Count the number of residues
write_xyz: true                             # Write out xyz files