name: qp
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - biopython
  - black
  - click
  - matplotlib
  - modeller
  - numpy
  - pandas
  - pip
  - requests
  - scipy
  - seaborn
  - pip:
      - sphinx_rtd_theme==0.5.2
      - sphinx-autoapi
      - https://github.com/revitron/revitron-sphinx-theme/archive/refs/tags/0.7.0.zip