name: qp
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - adjusttext
  - biopython
  - black
  - click
  - matplotlib
  - modeller
  - numpy
  - pandas
  - pip
  - python=3.8
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
    - sphinx==5.3.0
    - sphinx-rtd-theme==0.5.2
    - sphinx-autoapi==2.1.1
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip