name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn

    # Pip-only installs
  - pip:
    - sphinx==5.3.0
    - sphinx-rtd-theme==0.5.2
    - sphinx-autoapi==2.1.1
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
